export const constants = {
    language: 'ru',
    searchForm: document.querySelector('.search'),
    newsContainer: document.querySelector('.news-cards'),
    buttonShowMore: document.querySelector('.button_show-more'),
    results: document.querySelector('.results'),
    loader: document.querySelector('.loading'),
    founds: document.querySelector('.founds'),
    notFound: document.querySelector('.not-found'),
    error: document.querySelector('.search__error'),
    commitsContainer: document.querySelector('.github__commits-bar'),
    titleAnalytics: document.querySelector('.title_analytics'),
    errorApi: document.querySelector('.error'),
    errorApiText: document.querySelector('.error__text'),
    analyticsNumbers: document.querySelectorAll('.analytics__numbers-item_bold'),
    daysWeek: document.querySelectorAll('.infographics__day'),
    daysAccordance: document.querySelectorAll('.infographics__column'),
    week: ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'],
    graphicMonth: document.querySelector('.infographics__diagram-head-date'),
    months: ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь'],
    url: 'https://nomoreparties.co/news/v2/',
    key: '2356832b0876432c8814987efd07620a',
};